<?php

namespace AppBundle\Repository;

/**
 * bigeventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bigeventsRepository extends \Doctrine\ORM\EntityRepository
{
}
